openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://api.test'
paths:
  /api/lists/categories:
    get:
      summary: ''
      operationId: getApiListsCategories
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: 'Update Category From API'
                    -
                      id: 2
                      name: 'labore sed quisquam'
                    -
                      id: 3
                      name: 'recusandae quia ea'
                    -
                      id: 4
                      name: 'voluptas aut vitae'
                    -
                      id: 5
                      name: 'neque quia odio'
                    -
                      id: 6
                      name: 'voluptatum necessitatibus cum'
                    -
                      id: 7
                      name: 'impedit id molestias'
                    -
                      id: 8
                      name: 'ipsum libero earum'
                    -
                      id: 9
                      name: 'ipsam quis consequatur'
                    -
                      id: 10
                      name: 'cupiditate voluptates nesciunt'
                    -
                      id: 15
                      name: 'Categoria con fichero'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: 'Update Category From API'
                      -
                        id: 2
                        name: 'labore sed quisquam'
                      -
                        id: 3
                        name: 'recusandae quia ea'
                      -
                        id: 4
                        name: 'voluptas aut vitae'
                      -
                        id: 5
                        name: 'neque quia odio'
                      -
                        id: 6
                        name: 'voluptatum necessitatibus cum'
                      -
                        id: 7
                        name: 'impedit id molestias'
                      -
                        id: 8
                        name: 'ipsum libero earum'
                      -
                        id: 9
                        name: 'ipsam quis consequatur'
                      -
                        id: 10
                        name: 'cupiditate voluptates nesciunt'
                      -
                        id: 15
                        name: 'Categoria con fichero'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: 'Update Category From API'
      tags:
        - Categories
  /api/categories:
    get:
      summary: 'Get all categories'
      operationId: getAllCategories
      description: 'Getting the list of the categories'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Categories
    post:
      summary: ''
      operationId: postApiCategories
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: dignissimos
                  nullable: false
              required:
                - name
  '/api/categories/{id}':
    get:
      summary: 'Show Category'
      operationId: showCategory
      description: 'Get a category by ID'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Categories
    put:
      summary: ''
      operationId: putApiCategoriesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: voluptatem
                  nullable: false
              required:
                - name
    delete:
      summary: ''
      operationId: deleteApiCategoriesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Categories
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: 1
        required: true
        schema:
          type: integer
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/products:
    get:
      summary: ''
      operationId: getApiProducts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Products
tags:
  -
    name: Categories
    description: "\nApis for Managing category"
  -
    name: Endpoints
    description: ''
  -
    name: Products
    description: "\nApis for Managing products"
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
